Profile page
PastaCarbonara/Frontend pull request #43
Opened 2023-05-30 14:07 UTC by 07Marisa99

removing an account works now.

2023-05-30 14:52 UTC, mitchellvdhut requested changes

2023-05-30 14:52 UTC, mitchellvdhut commented on components/TextInputWithLabel.tsx
> +        <View {...inputProps}>
Ik denk dat dit niet verstandig is, nu krijgt de wrapper precies dezelfde styling als de text input die er in staat. Dat is voor nu alleen flex-grow en de height, maar dat voelt alsof het later problemen kan opleveren.

2023-05-30 14:52 UTC, mitchellvdhut commented on components/UserProfile/index.tsx
>      allTags: Array<object>;
Typing is missing

2023-05-30 14:52 UTC, mitchellvdhut commented on components/UserProfile/index.tsx
> +        <View style={tw`bg-bg_color min-h-full max-h-100 w-auto`}>
Change 100 to full

2023-05-30 14:52 UTC, mitchellvdhut commented on components/UserProfile/index.tsx
> +                                    .then((respon) => {
gekke afkorting respon

2023-05-30 14:52 UTC, mitchellvdhut commented on components/UserProfile/index.tsx
> +                        <Text style={tw`text-[#E81C00] text-xl mt-3 ml-3 grow`}>
Dit hoeft niet per se meteen aangepast te worden, maar hardcoded kleurcode

2023-05-30 14:52 UTC, mitchellvdhut commented on helpers/CookieHelper.ts
> +const deleteCookies = () => {
Als je de cookie wilt verwijderen lijkt het me niet dat je de value hoeft te weten, alleen maar de naam

2023-05-30 14:52 UTC, mitchellvdhut commented on screens/ProfileScreen.tsx
> +import userService from '../services/UserService';
dubbele import

2023-05-30 14:52 UTC, mitchellvdhut commented on services/HttpErrorHandling.ts
> +        console.log(response);
console.log

2023-05-30 14:52 UTC, mitchellvdhut commented on services/UserService.ts
> +        console.log('plz plant');
console.log

2023-06-01 12:02 UTC, mitchellvdhut requested changes

2023-06-01 12:02 UTC, mitchellvdhut commented on components/UserProfile/index.tsx
> +                            maxLength={42}
maxLength value random getal. Dylan zegt maak er 32 van

2023-06-01 12:02 UTC, mitchellvdhut commented on components/UserProfile/index.tsx
> +    }, [userName, userImage]);
Triggered zo te zien elke keer dat userName verandert. Dat is dus na elke keystroke. Terwijl je al een onBlur gebruikt om de userName te POSTen

2023-06-01 12:02 UTC, mitchellvdhut commented on components/UserProfile/index.tsx
> +                                    : console.log('Username is undefined')
console.log

2023-06-01 12:02 UTC, mitchellvdhut commented on components/UserProfile/index.tsx
>                              color="black"
Kleur matched niet design

2023-06-01 12:02 UTC, mitchellvdhut commented on components/UserProfile/index.tsx
> +                            style={tw`self-center m-3`}
Kleur matched niet design

2023-06-01 12:02 UTC, mitchellvdhut commented on components/UserProfile/index.tsx
>                              color="black"
Kleur matched niet design

2023-06-01 12:02 UTC, mitchellvdhut commented on helpers/CookieHelper.ts
> +        setCookie(cookieName, cookieValue, -1);
value is overbodig

2023-06-01 12:02 UTC, mitchellvdhut commented on helpers/CookieHelper.ts
> +const deleteCookie = (cookieName: string) => {
Wordt niet gebruikt

2023-06-01 12:02 UTC, mitchellvdhut commented on services/GroupService.ts
> +    const { data, error, isLoading } = useSWR(`/me/groups`, fetcher);
Waarom is dit veranderd

2023-06-01 12:02 UTC, mitchellvdhut commented on services/TagService.tsx
>  async function fetchAllTags() {
Deze functie kan weg toch?

2023-06-01 12:02 UTC, mitchellvdhut commented on services/UserService.ts
>      }
fetchFilters kan weg toch?

2023-06-01 12:47 UTC, 07Marisa99 commented on helpers/CookieHelper.ts
> +        setCookie(cookieName, cookieValue, -1);
niet als ik jouw functie gebruik, en jouw functie niet gebruiken maakt dubbele code

2023-06-01 12:47 UTC, 07Marisa99 commented on helpers/CookieHelper.ts
> +const deleteCookie = (cookieName: string) => {
jij wilde dat ik deze functie toevoegde, dus dat heb ik voor je gedaan.

2023-06-01 12:48 UTC, 07Marisa99 commented on services/GroupService.ts
> +    const { data, error, isLoading } = useSWR(`/me/groups`, fetcher);
don't remember, zal het terugzetten

2023-06-01 12:53 UTC, Marisa-Maylene commented on helpers/CookieHelper.ts
> +const deleteCookie = (cookieName: string) => {
jij wilde dat ik deze functie toevoegde, dus dat heb ik voor je gedaan.

2023-06-01 12:53 UTC, 07Marisa99 commented on helpers/CookieHelper.ts
> +        setCookie(cookieName, cookieValue, -1);
niet als ik jouw functie gebruik, en jouw functie niet gebruiken maakt dubbele code

2023-06-02 07:50 UTC, mitchellvdhut approved these changes

2023-06-02 10:20 UTC, merged